export const strings = [
  { type: "typescript", name: "TS", color: "#205aa1" },
  { type: "markdown", name: "MD", color: "#8c7c74" },
  { type: "lua", name: "Lua", color: "#000080" },
  { type: "sh", name: "sh", color: "#787878" },
  { type: "css", name: "CSS", color: "#461aa3" },
  { type: "yaml", name: "YAML", color: "#CA181D" },
  { type: "nix", name: "Nix", color: "#7E7EFF" },
  { type: "typescriptreact", name: "TSX", color: "#4d8ddb" },
  { type: "javascriptreact", name: "JSX", color: "#00B8DB" },
  { type: "json", name: "JSON", color: "#4f4e4d" },
  { type: "dockerfile", name: "Dockerfile", color: "#647e9e" },
  { type: "javascript", name: "JS", color: "#fcb50d" },
  { type: "html", name: "HTML", color: "#fc5d0d" },
  { type: "scss", name: "SCSS", color: "#f030b0" },
  { type: "python", name: "Python", color: "#1c7ae6" },
  { type: "astro", name: "Astro", color: "#e36927" },
  { type: "rust", name: "Rust", color: "#dda484" },
  { type: "toml", name: "Toml", color: "#9c4121" },
  { type: "markdown.mdx", name: "MDX", color: "##999999" },
];
