import Head from 'next/head'
import React, { useState } from 'react'
import Footer from './Footer'
import Navbar from './Navbar'
import useMediaQuery from '../hooks/useMediaQuery';
import { useEffect } from 'react';
import SideRight from './SideRight';
import SideLeft from './SideLeft';

interface Props{
    children: any
}


const Layout = ({children}: Props) => {

  const [selectedPage, setSelectedPage] = useState("home");
  const isAboveMediumScreens = useMediaQuery("(min-width: 1060px)");
  const [topPage, setTopPage] = useState(true);

  useEffect(() => {
    const handleScroll = () => {
      if(window.screenY === 0)setTopPage(true);
      if(window.screenY !== 0)setTopPage(false);

    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, [])

  return (
    <div>
    <Head>
    <title>Maicol H | Porfolio</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="theme-color" content="#2CBCE9" />
  </Head>

  <Navbar selectedPage={selectedPage} setSelectedPage={setSelectedPage} page={undefined} topPage={topPage}/>

  <div className='w-5/6 mx-auto md:h-full'>
   {isAboveMediumScreens && (
     <main>
      <SideRight/>
      <SideLeft/>
       {children}
     </main>
   )}
  </div>

  <footer>
    <Footer/>
  </footer>
</div>
  )
}

export default Layout